### ISSUE TITLE
Can you add sending SMS to phonenumber?

### ISSUE THREAD

**Issue by sriharshauppuluri** [chrisbarr/AmazonSNS-PHP-API#13]
I have a requirement to send a SMS to individual mobile numbers but you have written only for topicARN.

**Comment by chrisbarr** [comment]
Hi, you can add SMS mobile numbers as subscribers to a topic, then when you publish a message to that topic it will send it to all of the subscribed mobile numbers.
If that doesn't fit your use case you might be interested in some other providers that do this such as [Twilio](https://www.twilio.com/), [Nexmo](https://www.nexmo.com), [MessageBird](https://www.messagebird.com) etc.

Best of luck!

**Comment by sriharshauppuluri** [comment]
Thanks for sharing, I want to use SNS publish service with PhoneNumber key. I am able to send the request to server and getting response with MessageId.

**Comment by chrisbarr** [comment]
Have you been able to add the mobile numbers as subscribers? You can only publish to a topic.

**Comment by sriharsha1235** [comment]
Yes, but I want to send to individual members not to group.

**Comment by chrisbarr** [comment]
I don't think SNS is suitable for this use case I'm afraid.

**Comment by sriharsha1235** [comment]
Ok, Thanks. Is there any IRC for AWS SNS?

**Comment by chrisbarr** [comment]
There is a generic ##aws channel
