### ISSUE TITLE
listSubscriptions() or listSubscriptionsByTopic() do not work with the returned NextToken from previous call

### ISSUE THREAD

**Issue by vdchristelle** [chrisbarr/AmazonSNS-PHP-API#14]
1. the NextToken does not get returned by these functions, a bit hard if you want your next request to pass the returned NextToken param, so might be better to return it ;)
```
if(isset($resultXml->ListSubscriptionsResult->NextToken)) {
    $return->nexttoken = $resultXml->ListSubscriptionsResult->NextToken;
}
$return->members = $this->_processXmlToArray($subs);
return $return;
```
2. Even when you change the return of these functions and use the returned NextToken to pass into the next call, AWS returns error: "SNS returned the error "SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details." and code 403". 

Something goes wrong in the Signature creation... Any ideas?

**Comment by chrisbarr** [comment]
Hi sorry for the delay, does afc17bf4 fix this ok?

As for the problem with signature creation, I didn't get the same problem. I could use the nextToken to fetch the next page of results.
