### ISSUE TITLE
Fatal error: Uncaught exception 'APIException' with message 'There was a problem executing this request'

### ISSUE THREAD

**Issue by iyasilias** [chrisbarr/AmazonSNS-PHP-API#16]
Run your sample code, got this error:

> Fatal error: Uncaught exception 'APIException' with message 'There was a problem executing this request' in /Applications/XAMPP/xamppfiles/htdocs/dummyserver/vendor/chrisbarr/amazon-sns-php-api/lib/AmazonSNS.php:567 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/dummyserver/vendor/chrisbarr/amazon-sns-php-api/lib/AmazonSNS.php(177): AmazonSNS->_request('CreateTopic', Array) #1 /Applications/XAMPP/xamppfiles/htdocs/dummyserver/server1/sns.php(9): AmazonSNS->createTopic('My New SNS Topi...') #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/dummyserver/vendor/chrisbarr/amazon-sns-php-api/lib/AmazonSNS.php on line 567

**Comment by chrisbarr** [comment]
Ouch, have you set the `AMAZON_ACCESS_KEY_ID`, `AMAZON_SECRET_ACCESS_KEY` values?

**Comment by iyasilias** [comment]
Yes, i've setup the values..

**Comment by iyasilias** [comment]
As mentioned by ctg3 in issue #3  , at line 548 I put this code
`curl_setopt($ch, CURLOPT_CAINFO, '/Applications/XAMPP/xamppfiles/htdocs/cacert.pem');`
(where I put the cacert.pem file)
Then the code works fine. (Of course this is just a workaround and not to be used in production)

Just a side note, if I catch the error, the output is:
`There was an unknown problem with the API, returned code 0` (In case someone googling with the error message)

**Comment by chrisbarr** [comment]
Interesting, thanks for letting me know. I don't understand yet why some people experience that issue and not others, I guess it's to do with the underlying libcurl package.

I'm planning on improving the error messages as they're a bit unhelpful at the moment.
