### ISSUE TITLE
Hardcoded endpoints

### ISSUE THREAD

**Issue by chrisharrison** [chrisbarr/AmazonSNS-PHP-API#18]
I've been using this library for a while. But I now have the requirement to connect to a Dockerised local version of SNS (rather than the real live AWS service).

Obviously, it's impossible with this library because the endpoints are derived from the region in the constructor. I'm currently working on adapting this library so the constructor will look like this:

```php
public function __construct(string $accessKey, string $secretKey, string $endpoint) {
```

I will then provide a factory method to construct the client using a region:
```php
public static function fromAwsCredentials(string $accessKey, string $secretKey, string $region): AmazonSNS {
```

This method would then encapsulate the logic of converting the region into an endpoint. I'd probably also inject the functionality of converting the region into an endpoint using a `RegionHandler` class or something so that users can create their own providers (for handling new regions or whatever).

Obviously this is making a breaking change and is almost become another library altogether. But I will keep your `_request` method and all the API methods themselves intact.

So my question is, do you want me to do a PR for all of this? And make it a new major version? Or would you rather I just created my own GitHub/Packagist for this and go our separate ways?

**Comment by chrisbarr** [comment]
Awesome, I didn't realise a Dockerised version of SNS existed, will have to check that out!

How about just adding a `setEnpoint()` method that allows you to manually override the URL? I created PR #19 - if that's helps you I'll merge and create a new release.

It's nice to know people are still using this project 😄
