### ISSUE TITLE
Problem with http_build_query

### ISSUE THREAD

**Issue by vladaman** [chrisbarr/AmazonSNS-PHP-API#4]
Not sure why, but on one of our servers http_build_query() function was separating URL parameters with &amps; instead of &.

Changing line to this solved the issue.
`$request = $this->protocol . $this->endpoint . '/?' . http_build_query($params,'','&');`

Second issue I found was that the Timestamp should include milliseconds:
`$params['Timestamp'] = gmdate('Y-m-d\TH:i:s.000\Z');`

Otherwhise great class. I love these simple single purpose classes instead of large SDKs.

**Comment by chrisbarr** [comment]
Thanks @vladaman :) Maybe `arg_separator.output` in the php.ini file was set differently, though that would be unusual.
